NetStarter/Controllers/UserAttachmentTypeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using NetStarter.Models;
using NetStarter.Resources;

namespace NetStarter.Controllers
{
    [Authorize]
    public class UserAttachmentTypeController : Controller
    {
        private DefaultDBContext db = new DefaultDBContext();
        private GeneralController general = new GeneralController();

        [CustomAuthorizeFilter(ProjectEnum.ModuleCode.UserAttachmentType, "true", "", "", "")]
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult GetPartialViewUserAttachmentType()
        {
            UserAttachmentTypeListing userAttachmentTypeListing = new UserAttachmentTypeListing();
            userAttachmentTypeListing.Listing = ReadUserAttachmentTypes();
            return PartialView("~/Views/UserAttachmentType/_MainList.cshtml", userAttachmentTypeListing);
        }

        public List<GlobalOptionSetViewModel> ReadUserAttachmentTypes()
        {
            List<GlobalOptionSetViewModel> result = new List<GlobalOptionSetViewModel>();
            result = (from t1 in db.GlobalOptionSets
                      where t1.Type == "UserAttachment" && t1.Status == "Active"
                      select new GlobalOptionSetViewModel
                      {
                          Id = t1.Id,
                          Code = t1.Code,
                          DisplayName = t1.DisplayName,
                          OptionOrder = t1.OptionOrder,
                          SystemDefault = t1.SystemDefault
                      }).ToList();
            return result;
        }

        public GlobalOptionSetViewModel GetViewModel(string Id, string type)
        {
            GlobalOptionSetViewModel model = new GlobalOptionSetViewModel();
            using (DefaultDBContext db = new DefaultDBContext())
            {
                GlobalOptionSet globalOptionSet = db.GlobalOptionSets.Where(a => a.Id == Id).FirstOrDefault();
                model.Id = globalOptionSet.Id;
                model.Code = globalOptionSet.Code;
                model.DisplayName = globalOptionSet.DisplayName;
                model.Status = globalOptionSet.Status;
                model.OptionOrder = globalOptionSet.OptionOrder;
                model.SystemDefault = globalOptionSet.SystemDefault;
                model.IsoUtcCreatedOn = globalOptionSet.IsoUtcCreatedOn;
                model.IsoUtcModifiedOn = globalOptionSet.IsoUtcModifiedOn;
                if (type == "View")
                {
                    model.CreatedAndModified = general.GetCreatedAndModified(globalOptionSet.CreatedBy, globalOptionSet.IsoUtcCreatedOn, globalOptionSet.ModifiedBy, globalOptionSet.IsoUtcModifiedOn);
                }
            }
            return model;
        }

        [CustomAuthorizeFilter(ProjectEnum.ModuleCode.UserAttachmentType, "", "true", "true", "")]
        public ActionResult Edit(string Id)
        {
            GlobalOptionSetViewModel model = new GlobalOptionSetViewModel();
            if (Id != null)
            {
                model = GetViewModel(Id, "Edit");
            }
            else
            {
                //display order
                int? maxOrder = db.GlobalOptionSets.Where(a => a.Type == "UserAttachment" && a.Status == "Active").Select(a => a.OptionOrder).OrderByDescending(a => a.Value).FirstOrDefault();
                model.OptionOrder = maxOrder + 1;
            }
            return View(model);
        }

        [CustomAuthorizeFilter(ProjectEnum.ModuleCode.UserAttachmentType, "true", "", "", "")]
        public ActionResult ViewRecord(string Id)
        {
            GlobalOptionSetViewModel model = new GlobalOptionSetViewModel();
            if (Id != null)
            {
                model = GetViewModel(Id, "View");
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(GlobalOptionSetViewModel model)
        {
            ValidateModel(model);

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            SaveRecord(model);
            TempData["NotifySuccess"] = Resource.RecordSavedSuccessfully;
            return RedirectToAction("index");
        }

        public void ValidateModel(GlobalOptionSetViewModel model)
        {
            if (model != null)
            {
                bool duplicated = false;
                if (model.Id != null)
                {
                    duplicated = db.GlobalOptionSets.Where(a => a.DisplayName == model.DisplayName && a.Type == "UserAttachment" && a.Id != model.Id).Any();
                }
                else
                {
                    duplicated = db.GlobalOptionSets.Where(a => a.DisplayName == model.DisplayName && a.Type == "UserAttachment").Select(a => a.Id).Any();
                }

                if (duplicated == true)
                {
                    ModelState.AddModelError("DisplayName", Resource.UserAttachmentTypeNameAlreadyExist);
                }
            }
        }

        public void SaveRecord(GlobalOptionSetViewModel model)
        {
            if (model != null)
            {
                Regex sWhitespace = new Regex(@"\s+");
                //edit
                if (model.Id != null)
                {
                    GlobalOptionSet globalOptionSet = db.GlobalOptionSets.Where(a => a.Id == model.Id).FirstOrDefault();
                    globalOptionSet.Code = sWhitespace.Replace(model.DisplayName, "");
                    globalOptionSet.DisplayName = model.DisplayName;
                    globalOptionSet.OptionOrder = model.OptionOrder;
                    globalOptionSet.Type = "UserAttachment";
                    globalOptionSet.Status = "Active";
                    globalOptionSet.ModifiedBy = User.Identity.GetUserId();
                    globalOptionSet.ModifiedOn = general.GetSystemTimeZoneDateTimeNow();
                    globalOptionSet.IsoUtcModifiedOn = general.GetIsoUtcNow();
                    db.Entry(globalOptionSet).State = EntityState.Modified;
                    db.SaveChanges();
                }
                //new record
                else
                {
                    GlobalOptionSet globalOptionSet = new GlobalOptionSet();
                    globalOptionSet.Id = Guid.NewGuid().ToString();
                    globalOptionSet.Code = sWhitespace.Replace(model.DisplayName, "");
                    globalOptionSet.DisplayName = model.DisplayName;
                    globalOptionSet.OptionOrder = model.OptionOrder;
                    globalOptionSet.Type = "UserAttachment";
                    globalOptionSet.Status = "Active";
                    globalOptionSet.CreatedBy = User.Identity.GetUserId();
                    globalOptionSet.CreatedOn = general.GetSystemTimeZoneDateTimeNow();
                    globalOptionSet.IsoUtcCreatedOn = general.GetIsoUtcNow();
                    globalOptionSet.SystemDefault = false;
                    db.GlobalOptionSets.Add(globalOptionSet);
                    db.SaveChanges();
                }
            }
        }

        [CustomAuthorizeFilter(ProjectEnum.ModuleCode.UserAttachmentType, "", "", "", "true")]
        public ActionResult Delete(string Id)
        {
            try
            {
                if (Id != null)
                {
                    GlobalOptionSet globalOptionSet = db.GlobalOptionSets.Where(a => a.Id == Id).FirstOrDefault();
                    if (globalOptionSet != null)
                    {
                        db.GlobalOptionSets.Remove(globalOptionSet);
                        db.SaveChanges();
                    }
                }
                TempData["NotifySuccess"] = Resource.RecordDeletedSuccessfully;
            }
            catch (Exception ex)
            {
                GlobalOptionSet globalOptionSet = db.GlobalOptionSets.Where(a => a.Id == Id).FirstOrDefault();
                if (globalOptionSet == null)
                {
                    TempData["NotifySuccess"] = Resource.RecordDeletedSuccessfully;
                }
                else
                {
                    TempData["NotifyFailed"] = Resource.FailedExceptionError;
                }
            }
            return RedirectToAction("index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (db != null)
                {
                    db.Dispose();
                    db = null;
                }
                if (general != null)
                {
                    general.Dispose();
                    general = null;
                }
            }

            base.Dispose(disposing);
        }
    }
}

NetStarter/Views/UserAttachmentType/Edit.cshtml
@model NetStarter.Models.GlobalOptionSetViewModel
@using NetStarter.Resources
@{
    ViewBag.Module = Resource.UserAttachmentType;
    if (string.IsNullOrEmpty(Model.Id))
    {
        ViewBag.Title = Resource.Add + " " + ViewBag.Module;
    }
    else
    {
        ViewBag.Title = Resource.Edit + " " + ViewBag.Module;
    }
    Layout = "~/Views/Shared/_LayoutAfterLogin.cshtml";
}

<div class="row">
    <div class="col-12">
        <div style="--bs-breadcrumb-divider: '>';">
            <ol class="breadcrumb m-0">
                <li class="breadcrumb-item fw-normal"><a class="color-primarycolor opacity-50" href="@Url.Action("index")">@ViewBag.Module</a></li>
                @if (!string.IsNullOrEmpty(Model.Id))
                {
                    <li class="breadcrumb-item fw-normal"><a class="color-primarycolor opacity-50" href="@Url.Action("viewrecord", new { Id = Model.Id})">@Resource.View @Resource.UserAttachmentType</a></li>
                }
                <li class="breadcrumb-item fw-normal active">@ViewBag.Title</li>
            </ol>
        </div>
        <div class="page-title-box d-sm-flex align-items-center justify-content-between pt-2">
            <h4 class="pagetitle mb-sm-0 fw600">@ViewBag.Title</h4>
        </div>
    </div>
</div>

@using (Html.BeginForm("Edit", "UserAttachmentType", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <section class="section mt-3">
        <div class="bg-white rounded p-3 p-lg-4 p-xl-5 shadow">
            <div class="row">
                <div class="col-md-6">
                    <div class="mb-3 text-break">
                        <div class="form-group">
                            @Html.LabelFor(model => model.DisplayName, htmlAttributes: new { @class = "form-label required fw600" })
                            @Html.EditorFor(model => model.DisplayName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DisplayName, "", new { @class = "invalid-message" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="mb-3 text-break">
                        <div class="form-group">
                            @Html.LabelFor(model => model.OptionOrder, htmlAttributes: new { @class = "form-label required fw600" })
                            @Html.EditorFor(model => model.OptionOrder, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.OptionOrder, "", new { @class = "invalid-message" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-12">
                <a type="button" class="btn btn-p8 bg-light hover-boxshadow me-1" href="@Url.Action("index")">@Resource.BackToList</a>
                <button type="submit" class="addnewbtn btn btn-p8 hover-boxshadow hover-bg-primarycolor">@Resource.Save</button>
            </div>
        </div>
    </section>
}

NetStarter/Views/UserAttachmentType/Index.cshtml
@model NetStarter.Models.UserAttachmentTypeListing
@using NetStarter.Models;
@using NetStarter.Resources
@{
    ViewBag.Module = Resource.UserAttachmentType;
    ViewBag.Title = ViewBag.Module;
    Layout = "~/Views/Shared/_LayoutAfterLogin.cshtml";
    ViewBag.TableIdPrefix = "userattachmenttype";
    CurrentUserPermission permission = User.Identity.IsAllowed(ProjectEnum.ModuleCode.UserAttachmentType.ToString());
}

<div class="row">
    <div class="col-12">
        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
            <h4 class="pagetitle mb-sm-0 fw600">@ViewBag.Title</h4>
        </div>
    </div>
</div>

<section class="section dashboard mt-3">
    <div class="bg-white rounded p-3 shadow">
        <div class="pb-2">
            <a class="addnewbtn btn btn-p8 hover-boxshadow hover-moveup hover-bg-primarycolor" href="@Url.Action("edit")"><i class="fa-solid fa-plus pe-1"></i> @Resource.AddNewRecord</a>
            <span id="exportToExcel" class="addnewbtn btn btn-p8 hover-boxshadow cursor-pointer hover-moveup hover-bg-primarycolor secondary-button"><i class="fa-solid fa-file-excel pe-1"></i> @Resource.ExporttoExcel</span>
            <span id="exportToPdf" class="addnewbtn btn btn-p8 hover-boxshadow cursor-pointer hover-moveup hover-bg-primarycolor secondary-button"><i class="fa-solid fa-file-pdf pe-1"></i> @Resource.ExporttoPdf</span>
        </div>
        <div class="row justify-content-between align-items-end pb-1">
            <div class="col-sm-7 col-xl-3">
                @Html.Partial("~/Views/Shared/_TableLengthDropDown.cshtml", new ViewDataDictionary { { "DropDownId", ViewBag.TableIdPrefix + "-tableDropDown" } })
            </div>
            <div class="col-xl-4"></div>
            <div class="col-xl-5 pt-2 pt-sm-0">
                <div id="searchinput" class="input-group flex-nowrap">
                    @Html.TextBox("search", "", htmlAttributes: new { type = "text", @class = "form-control", @placeholder = Resource.SearchDot })
                    <button type="button" class="input-group-text bg-transparent hover-bg-primarycolor hover-color-white" id="searchbtn"><i class="fa-solid fa-magnifying-glass pe-1"></i> @Resource.Search</button>
                    <button type="button" class="input-group-text bg-transparent hover-bg-primarycolor hover-color-white" id="resetbtn"><i class="fa-solid fa-rotate-left pe-1"></i> @Resource.Reset</button>
                </div>
            </div>
        </div>
        <div id="@ViewBag.TableIdPrefix-table-wrapper">
            <div class="table-responsive">
                <table id="@ViewBag.TableIdPrefix-table" class="table table-hover align-middle mb-0">
                    <thead class="table-light">
                        <tr>
                            <th class="thead"></th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                <div class="spinner d-flex justify-content-center align-items-center text-center color-primarycolor py-5">
                    <div class="spinner-border ml-auto" role="status" aria-hidden="true"></div><strong> &nbsp; @Resource.Loading </strong>
                </div>
            </div>
            <div class="dummyfooter row justify-content-between">
                <div class="col-md-6">@Resource.Showing0Entries</div>
                <div class="col-md-6 text-end">@Resource.Page0OfPage0</div>
            </div>
        </div>
    </div>
</section>


@section scripts{
    <script>
        var tableIdPrefix = "@ViewBag.TableIdPrefix";
        var canView = "@permission.ViewRight";
        var canAdd = "@permission.AddRight";
        var canEdit = "@permission.EditRight";
        var canDelete = "@permission.DeleteRight";

        $(document).ready(function(){
            var url = "@(Html.Raw(Url.Action("GetPartialViewUserAttachmentType", "UserAttachmentType")))";
            $("#" + tableIdPrefix +"-table").load(url, function(responseTxt, statusTxt, xhr){
                if (statusTxt == "success") {
                    hideDummySpinnerHeaderFooter(tableIdPrefix+"-table-wrapper");
                }
                if (statusTxt == "error") {
                    //no record in database
                    if (xhr.status == 500) {
                        hideDummySpinnerHeaderFooter(tableIdPrefix+"-table-wrapper");
                        var table = $("#" + tableIdPrefix +"-table").DataTable({ dom: 'rtip', "pageLength": 10 });
                    }
                }
              });
        });
    </script>
}

NetStarter/Views/UserAttachmentType/ViewRecord.cshtml
@model NetStarter.Models.GlobalOptionSetViewModel
@using NetStarter.CustomHelper
@using NetStarter.Models
@using NetStarter.Resources
@{
    ViewBag.Module = Resource.UserAttachmentType;
    ViewBag.Title = Resource.View + "  " + ViewBag.Module;
    Layout = "~/Views/Shared/_LayoutAfterLogin.cshtml";
    CurrentUserPermission permission = User.Identity.IsAllowed(ProjectEnum.ModuleCode.UserAttachmentType.ToString());
}

<div class="row">
    <div class="col-12">
        <div style="--bs-breadcrumb-divider: '>';">
            <ol class="breadcrumb m-0">
                <li class="breadcrumb-item fw-normal"><a class="color-primarycolor opacity-50" href="@Url.Action("index")">@ViewBag.Module</a></li>
                <li class="breadcrumb-item fw-normal active">@ViewBag.Title</li>
            </ol>
        </div>
        <div class="page-title-box d-sm-flex align-items-center justify-content-between pt-2">
            <h4 class="pagetitle mb-sm-0 fw600">@ViewBag.Title</h4>
            <div class="d-flex">
                @if (Model.SystemDefault == false && permission.EditRight)
                {
                    <span class="fs-19"><a href="@Url.Action("edit", new { Id = Model.Id })"><i class="fa-solid fa-edit text-edit hover-color-secondarycolor" data-bs-toggle="tooltip" data-bs-placement="top" title="@Resource.Edit"></i></a></span>
                }
                @if (Model.SystemDefault == false && permission.DeleteRight)
                {
                    <span class="fs-19">&nbsp; <i onclick="triggerDeleteConfirmationModal('@Model.DisplayName','@Url.Action("delete", new { id= Model.Id})')" class="fa-solid fa-trash-can text-delete cursor-pointer hover-color-secondarycolor" data-bs-toggle="tooltip" data-bs-placement="top" title="@Resource.Delete"></i></span>
                }
            </div>
        </div>
    </div>
</div>

<section class="section mt-3">
    <div class="bg-white rounded p-3 p-lg-4 p-xl-5 shadow">
        <h2 class="fs-20 fw600 mb-4">@ViewBag.Module @Resource.Information</h2>
        <div class="row">
            <div class="col-md-6">
                <div class="mb-3 text-break">
                    <div>@Html.LabelFor(model => model.DisplayName, htmlAttributes: new { @class = "fw600" })</div>
                    <div>@Html.DisplayFor(model => model.DisplayName, new { htmlAttributes = new { @class = "form-control d-block" } })</div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="mb-3 text-break">
                    <div>@Html.LabelFor(model => model.OptionOrder, htmlAttributes: new { @class = "fw600" })</div>
                    <div>@Html.DisplayFor(model => model.OptionOrder, new { htmlAttributes = new { @class = "form-control" } })</div>
                </div>
            </div>
        </div>
    </div>
    <div class="bg-white rounded p-3 p-lg-4 p-xl-5 shadow mt-4">
        <h2 class="fs-20 fw600 mb-4">@Resource.OtherInformation</h2>
        <div class="row">
            <div class="col-md-6">
                <div class="mb-3 text-break">
                    <div>@Html.LabelFor(model => model.CreatedAndModified.CreatedByName, htmlAttributes: new { @class = "fw600" })</div>
                    <div>@Html.DisplayFor(model => model.CreatedAndModified.CreatedByName, new { htmlAttributes = new { @class = "form-control" } })</div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="mb-3 text-break">
                    <div>@Html.LabelFor(model => model.CreatedAndModified.FormattedCreatedOn, htmlAttributes: new { @class = "fw600" })</div>
                    <div>@Html.DisplayFor(model => model.CreatedAndModified.FormattedCreatedOn, new { htmlAttributes = new { @class = "form-control" } })</div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="mb-3 text-break">
                    <div>@Html.LabelFor(model => model.CreatedAndModified.ModifiedByName, htmlAttributes: new { @class = "fw600" })</div>
                    <div>@Html.DisplayFor(model => model.CreatedAndModified.ModifiedByName, new { htmlAttributes = new { @class = "form-control" } })</div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="mb-3 text-break">
                    <div>@Html.LabelFor(model => model.CreatedAndModified.FormattedModifiedOn, htmlAttributes: new { @class = "fw600" })</div>
                    <div>@Html.DisplayFor(model => model.CreatedAndModified.FormattedModifiedOn, new { htmlAttributes = new { @class = "form-control" } })</div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-12">
            <a class="btn btn-p8 bg-light hover-boxshadow me-1" href="@Url.Action("index")">@Resource.BackToList</a>
            @if (Model.SystemDefault == false && permission.EditRight)
            {
                <a class="btn btn-p8 hover-boxshadow me-1 addnewbtn hover-bg-primarycolor" href="@Url.Action("edit", new { Id = Model.Id})">@Resource.Edit @ViewBag.Module</a>
            }
        </div>
    </div>
</section>

NetStarter/Views/UserAttachmentType/_MainList.cshtml
@model NetStarter.Models.UserAttachmentTypeListing
@using NetStarter.Resources
<thead class="table-light">
    <tr>
        <th class="thead">@Html.DisplayNameFor(model => model.Listing[0].OptionOrder) <i class="fa-solid fa-circle-info text-info ps-2" data-bs-toggle="tooltip" data-bs-placement="right" title="The order of user attachment type displayed in the drop down list"></i></th>
        <th class="thead">@Html.DisplayNameFor(model => model.Listing[0].DisplayName)</th>
        <th class="thead">@Resource.Actions <i class="fa-solid fa-circle-info text-info ps-2" data-bs-toggle="tooltip" data-bs-placement="right" title="@Resource.ProfilePictureAttachmentTypeCannotBeEditedOrDeleted"></i></th>
    </tr>
</thead>
<tbody>
    @foreach (var item in Model.Listing)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.OptionOrder)</td>
            <td><a class="fw600 color-primarycolor hover-color-secondarycolor" href="@Url.Action("viewrecord", new { Id = @Html.ValueFor(modelItem => item.Id) })">@Html.DisplayFor(modelItem => item.DisplayName)</a></td>
            <td>
                <div class="d-flex text-breakspaces actioncol">
                    @if (item.SystemDefault == false)
                    {
                        <span class="fs-19 canedit"><a href="@Url.Action("edit", new { Id = @Html.ValueFor(modelItem => item.Id) })"><i class="fa-solid fa-edit text-edit hover-color-secondarycolor" data-bs-toggle="tooltip" data-bs-placement="top" title="@Resource.Edit"></i></a> &nbsp;</span>
                        <span class="fs-19 candelete" onclick="triggerDeleteConfirmationModal('@item.DisplayName', '@Url.Action("delete", new { id= item.Id})')"><i class="fa-solid fa-trash-can text-delete hover-color-secondarycolor cursor-pointer" data-bs-toggle="tooltip" data-bs-placement="top" title="@Resource.Delete"></i></span>
                    }
                </div>
            </td>
        </tr>
    }
</tbody>

<script>
    var fileName = "@Resource.ListofUserAttachmentTypes";
    var indexLastColumn = $('#' + tableIdPrefix + '-table').find('tr')[0].cells.length - 1;
    //initialize datatable
    var table = $('#' + tableIdPrefix + '-table').DataTable({
        dom: 'Brtip',
        "pageLength": 10,
        //order: [[2, 'desc']],
        scrollY: 'auto',
        scrollX: 'auto',
        deferRender: true,
        scroller: true,
        buttons: [
            {
                extend: 'csv',
                title: fileName,
                exportOptions: { columns: getColumnsToBeExported(tableIdPrefix) }
            }, {
                extend: 'excel',
                title: fileName,
                exportOptions: { columns: getColumnsToBeExported(tableIdPrefix) }
            }, {
                extend: 'pdf',
                title: fileName,
                exportOptions: { columns: getColumnsToBeExported(tableIdPrefix) },
                customize: function (doc) {
                    var colCount = adjustPdfColWidth(tableIdPrefix);
                    doc.content[1].table.widths = colCount;
                }
            }
        ],
        "columnDefs": [{
            'targets': [indexLastColumn], // column index (start from 0)
            'orderable': false, // set orderable false for selected columns
        }]
    });

    if (canEdit == 'False') {
        $('#' + tableIdPrefix + '-table .canedit').hide();
    }
    if (canDelete == 'False') {
        $('#' + tableIdPrefix + '-table .candelete').hide();
    }

    $("#exportToExcel").click(function () {
        $(".buttons-excel").trigger("click");
    });
    $("#exportToPdf").click(function () {
        $(".buttons-pdf").trigger("click");
    });

    //initialize tooltip
    var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
    var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
        return new bootstrap.Tooltip(tooltipTriggerEl)
    })

    //event listener for search, reset, and "show 10 records" buttons
    document.getElementById("searchbtn").addEventListener("click", searchTable);
    document.getElementById("resetbtn").addEventListener("click", resetTable);

    function searchTable() {
        var valToSearch = document.getElementById("search").value;
        table.search(valToSearch).draw();
    }

    function resetTable() {
        document.getElementById("search").value = "";
        table.search("").draw();
    }

    //event listener for the "show 10 records" drop down list
    for (const option of document.querySelectorAll("#" + tableIdPrefix + "-tableDropDown .custom-option")) {
        option.addEventListener('click', function () {
            if (!this.classList.contains('selected')) {
                this.parentNode.querySelector('.custom-option.selected').classList.remove('selected');
                this.classList.add('selected');
                this.closest('.select').querySelector('.select__trigger span').textContent = this.textContent;
                let chosenValue = this.getAttribute("data-value");
                table.page.len(chosenValue).draw();
            }
        })
    }
</script>