NetStarter/Controllers/InitiatoryPleadingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using NetStarter.Models;
using NetStarter.Resources;

namespace NetStarter.Controllers
{
    [Authorize]
    public class InitiatoryPleadingController : Controller
    {
        private DefaultDBContext db = new DefaultDBContext();
        private GeneralController general = new GeneralController();

        [CustomAuthorizeFilter(ProjectEnum.ModuleCode.PreFiledCase, "true", "", "", "")]
        public ViewResult Index()
        {
            return View();
        }

        public ActionResult GetPartialViewInitiatoryPleadings()
        {
            string userId = User.Identity.GetUserId();
            InitiatoryPleadingListing theListing = new InitiatoryPleadingListing();
            theListing.Listing = ReadInitiatoryPleadings(userId);
            return PartialView("~/Views/InitiatoryPleading/_MainList.cshtml", theListing);
        }

        public List<InitiatoryPleadingModel> ReadInitiatoryPleadings(string userId)
        {
            List<InitiatoryPleadingModel> list = new List<InitiatoryPleadingModel>();
            list = (from t1 in db.InitiatoryPleadings
                    join t2 in db.AspNetUsers on t1.CreatedBy equals t2.Id
                    join t3 in db.UserProfiles on t2.Id equals t3.AspNetUserId
                    where t1.CreatedBy == userId
                    orderby t1.CreatedOn descending
                    select new InitiatoryPleadingModel()
                    {
                        Id = t1.Id,
                        DocumentName = t1.DocumentName,
                        Description = t1.Description,
                        Barcode = t1.Barcode,
                        CreatedBy = t3.FirstName + " " + t3.LastName,
                        CreatedOn = t1.CreatedOn
                    }).ToList();
            return list;
        }

        public List<InitiatoryPleadingAttachment> ReadInitiatoryPleadingAttachments(string initiatoryPleadingId)
        {
            List<InitiatoryPleadingAttachment> list = new List<InitiatoryPleadingAttachment>();
            list = db.InitiatoryPleadingAttachments.Where(x => x.InitiatoryPleadingId == initiatoryPleadingId).ToList();
            return list;
        }

        public InitiatoryPleadingModel GetViewModel(string Id, string type)
        {
            InitiatoryPleadingModel model = new InitiatoryPleadingModel();
            using (DefaultDBContext db = new DefaultDBContext())
            {
                InitiatoryPleading initiatoryPleading = db.InitiatoryPleadings.Where(a => a.Id == Id).FirstOrDefault();
                model.Id = initiatoryPleading.Id;
                model.DocumentName = initiatoryPleading.DocumentName;
                model.Description = initiatoryPleading.Description;
                model.Barcode = initiatoryPleading.Barcode;
                model.CreatedBy = db.UserProfiles.FirstOrDefault(x => x.AspNetUserId == initiatoryPleading.CreatedBy).FullName;
                model.CreatedOn = initiatoryPleading.CreatedOn;
                model.ModifiedBy = initiatoryPleading.ModifiedBy;
                model.ModifiedOn = initiatoryPleading.ModifiedOn;
                if (type == "View")
                {
                    model.CreatedAndModified = general.GetCreatedAndModified(initiatoryPleading.CreatedBy, initiatoryPleading.CreatedOn.ToString(), initiatoryPleading.ModifiedBy, initiatoryPleading.ModifiedOn.ToString());
                }
            }
            return model;
        }

        [CustomAuthorizeFilter(ProjectEnum.ModuleCode.InitiatoryPleading, "", "true", "true", "")]
        public ActionResult DeleteFile(string Id)
        {
            if (Id != null)
            {
                var attachment = db.InitiatoryPleadingAttachments.FirstOrDefault(x => x.Id == Id);
                db.InitiatoryPleadingAttachments.Remove(attachment);
                db.SaveChanges();

                if (System.IO.File.Exists(attachment.FileUrl))
                    System.IO.File.Delete(attachment.FileUrl);

                TempData["NotifySuccess"] = "File was deleted successfully.";
            }
            return Redirect(Request.UrlReferrer.ToString());
        }

        [CustomAuthorizeFilter(ProjectEnum.ModuleCode.InitiatoryPleading, "", "true", "true", "")]
        public ActionResult Edit(string Id)
        {
            InitiatoryPleadingModel model = new InitiatoryPleadingModel();
            if (Id != null)
            {
                model = GetViewModel(Id, "Edit");
            }
            model.Attachments = ReadInitiatoryPleadingAttachments(Id);
            return View(model);
        }

        [CustomAuthorizeFilter(ProjectEnum.ModuleCode.InitiatoryPleading, "true", "", "", "")]
        public ActionResult ViewRecord(string Id)
        {
            InitiatoryPleadingModel model = new InitiatoryPleadingModel();
            if (Id != null)
            {
                model = GetViewModel(Id, "View");
                model.Attachments = ReadInitiatoryPleadingAttachments(Id);
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(InitiatoryPleadingModel model)
        {
            ValidateModel(model);

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            SaveRecord(model);
            TempData["NotifySuccess"] = Resource.RecordSavedSuccessfully;
            return RedirectToAction("index");
        }

        public void ValidateModel(InitiatoryPleadingModel model)
        {
            if (model != null)
            {
                bool duplicated = false;
                if (model.Id != null)
                {
                    duplicated = db.InitiatoryPleadings.Where(a => a.DocumentName == model.DocumentName && a.Id != model.Id).Any();
                }
                else
                {
                    duplicated = db.InitiatoryPleadings.Where(a => a.DocumentName == model.DocumentName).Select(a => a.Id).Any();
                }

                if (duplicated == true)
                {
                    ModelState.AddModelError("DocumentName", Resource.RequestSubjectAlreadyExist);
                }
            }
        }

        public void SaveRecord(InitiatoryPleadingModel model)
        {
            string userId = User.Identity.GetUserId();

            if (model != null)
            {
                //edit
                if (model.Id != null)
                {
                    InitiatoryPleading initiatoryPleading = db.InitiatoryPleadings.Where(a => a.Id == model.Id).FirstOrDefault();
                    initiatoryPleading.DocumentName = model.DocumentName;
                    initiatoryPleading.Description = model.Description;
                    initiatoryPleading.Barcode = model.Barcode;
                    initiatoryPleading.ModifiedBy = userId;
                    initiatoryPleading.ModifiedOn = general.GetSystemTimeZoneDateTimeNow();
                    db.Entry(initiatoryPleading).State = EntityState.Modified;
                    db.SaveChanges();
                }
                //new record
                else
                {
                    InitiatoryPleading initiatoryPleading = new InitiatoryPleading();
                    initiatoryPleading.Id = Guid.NewGuid().ToString();
                    initiatoryPleading.DocumentName = model.DocumentName;
                    initiatoryPleading.Description = model.Description;
                    initiatoryPleading.Barcode = model.Barcode;
                    initiatoryPleading.CreatedBy = userId;
                    initiatoryPleading.CreatedOn = general.GetSystemTimeZoneDateTimeNow();
                    db.InitiatoryPleadings.Add(initiatoryPleading);
                    db.SaveChanges();

                    model.Id = initiatoryPleading.Id;
                }

                general.SaveInitiatoryPleadingAttachment(model.Documents, model.Id, User.Identity.GetUserId());
            }
        }

        [CustomAuthorizeFilter(ProjectEnum.ModuleCode.PreFiledCase, "", "", "", "true")]
        public ActionResult Delete(string Id)
        {
            try
            {
                if (Id != null)
                {
                    InitiatoryPleading initiatoryPleading = db.InitiatoryPleadings.Where(a => a.Id == Id).FirstOrDefault();
                    if (initiatoryPleading != null)
                    {
                        db.InitiatoryPleadings.Remove(initiatoryPleading);
                        db.SaveChanges();
                    }
                }
                TempData["NotifySuccess"] = Resource.RecordDeletedSuccessfully;
            }
            catch (Exception ex)
            {
                InitiatoryPleading initiatoryPleading = db.InitiatoryPleadings.Where(a => a.Id == Id).FirstOrDefault();
                if (initiatoryPleading == null)
                {
                    TempData["NotifySuccess"] = Resource.RecordDeletedSuccessfully;
                }
                else
                {
                    TempData["NotifyFailed"] = Resource.FailedExceptionError;
                }
            }
            return RedirectToAction("index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (db != null)
                {
                    db.Dispose();
                    db = null;
                }
                if (general != null)
                {
                    general.Dispose();
                    general = null;
                }
            }

            base.Dispose(disposing);
        }
    }
}

NetStarter/Views/InitiatoryPleading/Edit.cshtml
@model NetStarter.Models.InitiatoryPleadingModel
@using NetStarter.CustomHelper
@using NetStarter.Resources
@{
    if (string.IsNullOrEmpty(Model.Id))
    {
        ViewBag.Title = Resource.Add + " Initiatory Pleading";
    }
    else
    {
        ViewBag.Title = Resource.Edit + " Initiatory Pleading";
    }
    Layout = "~/Views/Shared/_LayoutAfterLogin.cshtml";
}

<div class="row">
    <div class="col-12">
        <div style="--bs-breadcrumb-divider: '>';">
            <ol class="breadcrumb m-0">
                <li class="breadcrumb-item fw-normal">
                    <a class="color-primarycolor opacity-50" href="@Url.Action("index")">Initiatory Pleadings</a>
                </li>
                @if (!string.IsNullOrEmpty(Model.Id))
                {
                    <li class="breadcrumb-item fw-normal"><a class="color-primarycolor opacity-50" href="@Url.Action("viewrecord", new { Id = Model.Id})">View Initiatory Pleading</a></li>
                }
                <li class="breadcrumb-item fw-normal active">@ViewBag.Title</li>
            </ol>
        </div>
        <div class="page-title-box d-sm-flex align-items-center justify-content-between pt-2">
            <h4 class="pagetitle mb-sm-0 fw600">@ViewBag.Title</h4>
        </div>
    </div>
</div>

@using (Html.BeginForm("Edit", "InitiatoryPleading", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new
{
    @class = "form-horizontal",
    role = "form",
    enctype = "multipart/form-data"
}))
{
    <section class="section mt-3">
        <div class="bg-white rounded p-3 p-lg-4 p-xl-5 shadow">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.DocumentName, htmlAttributes: new { @class = "form-label required fw600" })
                        @Html.EditorFor(model => model.DocumentName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DocumentName, "", new { @class = "invalid-message" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Barcode, htmlAttributes: new { @class = "form-label required fw600" })
                        @Html.EditorFor(model => model.Barcode, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Barcode, "", new { @class = "invalid-message" })
                    </div>
                </div>
            </div>
            <div class="row mt-2">
                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "form-label fw600" })
                    @Html.TextAreaFor(model => model.Description, htmlAttributes: new { @class = "form-control", @rows = "3" })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "invalid-message" })
                </div>
            </div>
            <div class="row mt-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.Documents, htmlAttributes: new { @class = "form-label fw600" }) <i class="fa-solid fa-circle-info align-middle" data-bs-toggle="tooltip" data-bs-placement="top" title="You can upload multiple files here."></i>
                    @Html.TextBox("Documents", "", new { @type = "file", @class = "form-control", @multiple = true })
                    @Html.ValidationMessageFor(model => model.Documents, "", new { @class = "invalid-message" })
                </div>
            </div>
            <hr />
            @if (Model.Attachments != null && Model.Attachments.Count > 0)
            {
                <p><strong>List of Uploaded Document(s)</strong></p>
                <ul class="list-group">
                    @foreach (var item in Model.Attachments)
                    {
                        <li class="list-group-item">
                            @Html.DisplayFor(modelItem => item.UniqueFileName)
                            <span class="fs-19 canedit">
                                <a href="~/Documents/@item.UniqueFileName" data-bs-placement="right" title="Download" download>
                                    <i class="fa-solid fa-download text-edit hover-color-secondarycolor" data-bs-toggle="tooltip" data-bs-placement="top" title="Download"></i>
                                </a> &nbsp;
                            </span>
                            <span class="fs-19 candelete" onclick="triggerDeleteConfirmationModal('@item.UniqueFileName', '@Url.Action("deletefile", new { id= item.Id})')">
                                <i class="fa-solid fa-trash-can text-delete hover-color-secondarycolor cursor-pointer" data-bs-toggle="tooltip" data-bs-placement="top" title="Delete"></i>
                            </span>
                        </li>
                    }
                </ul>
            }
            else
            {
                <i>No uploaded document yet.</i>
            }
        </div>
        <div class="row mt-4">
            <div class="col-12">
                <a type="button" class="btn btn-p8 bg-light hover-boxshadow me-1" href="@Url.Action("index")">@Resource.BackToList</a>
                @if (Model.SystemDefault == false)
                {

                    <button type="submit" class="addnewbtn btn btn-p8 hover-boxshadow hover-bg-primarycolor">@Resource.Save</button>
                }
            </div>
        </div>
    </section>
}

NetStarter/Views/InitiatoryPleading/Index.cshtml
@model NetStarter.Models.InitiatoryPleadingListing
@using NetStarter.Models;
@using NetStarter.Resources
@{
    ViewBag.Title = Resource.InitiatoryPleadings;
    Layout = "~/Views/Shared/_LayoutAfterLogin.cshtml";
    ViewBag.TableIdPrefix = "initiatorypleading";
    CurrentUserPermission permission = User.Identity.IsAllowed(ProjectEnum.ModuleCode.InitiatoryPleading.ToString());
}

<div class="row">
    <div class="col-12">
        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
            <h4 class="pagetitle mb-sm-0 fw600">@ViewBag.Title</h4>
        </div>
    </div>
</div>

<section class="section dashboard mt-3">
    <div class="bg-white rounded p-3 shadow">
        <div class="pb-2">
            <a class="addnewbtn btn btn-p8 hover-boxshadow hover-moveup hover-bg-primarycolor" href="@Url.Action("edit")"><i class="fa-solid fa-plus pe-1"></i> @Resource.AddNewRecord</a>
            <span id="exportToExcel" class="addnewbtn btn btn-p8 hover-boxshadow cursor-pointer hover-moveup hover-bg-primarycolor secondary-button"><i class="fa-solid fa-file-excel pe-1"></i> @Resource.ExporttoExcel</span>
            <span id="exportToPdf" class="addnewbtn btn btn-p8 hover-boxshadow cursor-pointer hover-moveup hover-bg-primarycolor secondary-button"><i class="fa-solid fa-file-pdf pe-1"></i> @Resource.ExporttoPdf</span>
        </div>
        <div class="row justify-content-between align-items-end pb-1">
            <div class="col-sm-7 col-xl-3">
                @Html.Partial("~/Views/Shared/_TableLengthDropDown.cshtml", new ViewDataDictionary { { "DropDownId", ViewBag.TableIdPrefix + "-tableDropDown" } })
            </div>
            <div class="col-xl-4"></div>
            <div class="col-xl-5 pt-2 pt-sm-0">
                <div id="searchinput" class="input-group flex-nowrap">
                    @Html.TextBox("search", "", htmlAttributes: new { type = "text", @class = "form-control", @placeholder = Resource.SearchDot })
                    <button type="button" class="input-group-text bg-transparent hover-bg-primarycolor hover-color-white" id="searchbtn"><i class="fa-solid fa-magnifying-glass pe-1"></i> @Resource.Search</button>
                    <button type="button" class="input-group-text bg-transparent hover-bg-primarycolor hover-color-white" id="resetbtn"><i class="fa-solid fa-rotate-left pe-1"></i> @Resource.Reset</button>
                </div>
            </div>
        </div>
        <div id="@ViewBag.TableIdPrefix-table-wrapper">
            <div class="table-responsive">
                <table id="@ViewBag.TableIdPrefix-table" class="table table-hover align-middle mb-0">
                    <thead class="table-light">
                        <tr>
                            <th class="thead"></th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                <div class="spinner d-flex justify-content-center align-items-center text-center color-primarycolor py-5">
                    <div class="spinner-border ml-auto" role="status" aria-hidden="true"></div><strong> &nbsp; @Resource.Loading </strong>
                </div>
            </div>
            <div class="dummyfooter row justify-content-between">
                <div class="col-md-6">@Resource.Showing0Entries</div>
                <div class="col-md-6 text-end">@Resource.Page0OfPage0</div>
            </div>
        </div>
    </div>
</section>

@section scripts{
    <script>
        var tableIdPrefix = "@ViewBag.TableIdPrefix";
        var canView = "@permission.ViewRight";
        var canAdd = "@permission.AddRight";
        var canEdit = "@permission.EditRight";
        var canDelete = "@permission.DeleteRight";

        $(document).ready(function(){
            var url = "@(Html.Raw(Url.Action("GetPartialViewInitiatoryPleadings", "InitiatoryPleading")))";
            $("#" + tableIdPrefix +"-table").load(url, function(responseTxt, statusTxt, xhr){
                if (statusTxt == "success") {
                    hideDummySpinnerHeaderFooter(tableIdPrefix+"-table-wrapper");
                }
                if (statusTxt == "error") {
                    //no record in database
                    if (xhr.status == 500) {
                        hideDummySpinnerHeaderFooter(tableIdPrefix+"-table-wrapper");
                        var table = $("#" + tableIdPrefix +"-table").DataTable({ dom: 'rtip', "pageLength": 10 });
                    }
                }
              });
        });
    </script>
}

NetStarter/Views/InitiatoryPleading/ViewRecord.cshtml
@model NetStarter.Models.InitiatoryPleadingModel
@using NetStarter.CustomHelper
@using NetStarter.Models
@using NetStarter.Resources
@{
    ViewBag.Title = "View Initiatory Pleading";
    ViewBag.Module = "Initiatory Pleading";
    Layout = "~/Views/Shared/_LayoutAfterLogin.cshtml";
    CurrentUserPermission permission = User.Identity.IsAllowed(ProjectEnum.ModuleCode.InitiatoryPleading.ToString());
}

<div class="row">
    <div class="col-12">
        <div style="--bs-breadcrumb-divider: '>';">
            <ol class="breadcrumb m-0">
                <li class="breadcrumb-item fw-normal"><a class="color-primarycolor opacity-50" href="@Url.Action("index")">Initiatory Pleadings</a></li>
                <li class="breadcrumb-item fw-normal active">@ViewBag.Title</li>
            </ol>
        </div>
        <div class="page-title-box d-sm-flex align-items-center justify-content-between pt-2">
            <h4 class="pagetitle mb-sm-0 fw600">@ViewBag.Title</h4>
            <div class="d-flex">
                @if (permission.EditRight && Model.SystemDefault == false)
                {
                    <span class="fs-19">
                    <a href="@Url.Action("edit", new { Id = Model.Id })">
                        <i class="fa-solid fa-edit text-edit hover-color-secondarycolor" data-bs-toggle="tooltip" data-bs-placement="top" title="@Resource.Edit"></i></a>
                    </span>
                }
                @if (permission.DeleteRight && Model.SystemDefault == false)
                {
                    <span class="fs-19">&nbsp; <i onclick="triggerDeleteConfirmationModal('@Model.DocumentName', '@Url.Action("delete", new { id=Model.Id})')" class="fa-solid fa-trash-can text-delete cursor-pointer hover-color-secondarycolor" data-bs-toggle="tooltip" data-bs-placement="top" title="@Resource.Delete"></i></span>
                }
            </div>
        </div>
    </div>
</div>

<section class="section mt-3">
    <div class="bg-white rounded p-3 p-lg-4 p-xl-5 shadow">
        <h2 class="fs-20 fw600 mb-4">@ViewBag.Module @Resource.Information</h2>
        <div class="row">
            <div class="mb-3 text-break">
                <div>@Html.LabelFor(model => model.DocumentName, htmlAttributes: new { @class = "fw600" })</div>
                <div>@Html.DisplayFor(model => model.DocumentName, new { htmlAttributes = new { @class = "form-control" } })</div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="mb-3 text-break">
                    <div>@Html.LabelFor(model => model.Barcode, htmlAttributes: new { @class = "fw600" })</div>
                    <div>@Html.DisplayFor(model => model.Barcode, new { htmlAttributes = new { @class = "form-control" } })</div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="mb-3 text-break">
                    <div><label class="fw600" for="CreatedOn">Date Created</label></div>
                    <div>@Html.DisplayFor(model => model.CreatedOn, new { htmlAttributes = new { @class = "form-control d-block" } })</div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="mb-3 text-break">
                <div>@Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "fw600" })</div>
                <div>@Html.DisplayFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })</div>
            </div>
        </div>
        <div class="row">
            @if (Model.Attachments.Count > 0)
            {
                <p><strong>List of Uploaded Document(s)</strong></p>
                <ul class="list-group">
                    @foreach (var item in Model.Attachments)
                    {
                        <li class="list-group-item">
                            @Html.DisplayFor(modelItem => item.UniqueFileName)
                        </li>
                    }
                </ul>
            }
            else
            {
                <i>No uploaded document yet.</i>
            }
        </div>
    </div>
    <div class="bg-white rounded p-3 p-lg-4 p-xl-5 shadow mt-4">
        <h2 class="fs-20 fw600 mb-4">@Resource.OtherInformation</h2>
        <div class="row">
            <div class="col-md-6">
                <div class="mb-3 text-break">
                    <div>@Html.LabelFor(model => model.CreatedAndModified.CreatedByName, htmlAttributes: new { @class = "fw600" })</div>
                    <div>@Html.DisplayFor(model => model.CreatedAndModified.CreatedByName, new { htmlAttributes = new { @class = "form-control" } })</div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="mb-3 text-break">
                    <div>@Html.LabelFor(model => model.CreatedAndModified.FormattedCreatedOn, htmlAttributes: new { @class = "fw600" })</div>
                    <div>@Html.DisplayFor(model => model.CreatedAndModified.FormattedCreatedOn, new { htmlAttributes = new { @class = "form-control" } })</div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="mb-3 text-break">
                    <div>@Html.LabelFor(model => model.CreatedAndModified.ModifiedByName, htmlAttributes: new { @class = "fw600" })</div>
                    <div>@Html.DisplayFor(model => model.CreatedAndModified.ModifiedByName, new { htmlAttributes = new { @class = "form-control" } })</div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="mb-3 text-break">
                    <div>@Html.LabelFor(model => model.CreatedAndModified.FormattedModifiedOn, htmlAttributes: new { @class = "fw600" })</div>
                    <div>@Html.DisplayFor(model => model.CreatedAndModified.FormattedModifiedOn, new { htmlAttributes = new { @class = "form-control" } })</div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-12">
            <a class="btn btn-p8 bg-light hover-boxshadow me-1" href="@Url.Action("index")">@Resource.BackToList</a>
            @if (permission.EditRight && Model.SystemDefault == false)
            {
                <a class="btn btn-p8 hover-boxshadow me-1 addnewbtn hover-bg-primarycolor" href="@Url.Action("edit", new { Id = Model.Id})">@Resource.Edit @ViewBag.Module</a>
            }
        </div>
    </div>
</section>