NetStarter/Controllers/FiledCaseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using NetStarter.Models;
using NetStarter.Resources;

namespace NetStarter.Controllers
{
    [Authorize]
    public class FiledCaseController : Controller
    {
        private DefaultDBContext db = new DefaultDBContext();
        private GeneralController general = new GeneralController();

        [CustomAuthorizeFilter(ProjectEnum.ModuleCode.FiledCase, "true", "", "", "")]
        public ViewResult Index()
        {
            return View();
        }

        public ActionResult GetPartialViewFiledCases()
        {
            PreFiledCaseListing theListing = new PreFiledCaseListing();
            theListing.Listing = ReadFiledCases();
            return PartialView("~/Views/FiledCase/_MainList.cshtml", theListing);
        }

        public List<PreFiledCaseViewModel> ReadFiledCases()
        {
            List<PreFiledCaseViewModel> list = new List<PreFiledCaseViewModel>();
            list = (from t1 in db.PreFiledCases
                    join t2 in db.UserProfiles on t1.UserId equals t2.AspNetUserId
                    join t3 in db.GlobalOptionSets.Where(x => x.Type == "CaseType") on t1.CaseTypeId equals t3.Id
                    join t4 in db.GlobalOptionSets.Where(x => x.Type == "CaseNature") on t1.CaseNatureId equals t4.Id
                    join t5 in db.GlobalOptionSets.Where(x => x.Type == "FileCaseStatus") on t1.FileCaseStatusId equals t5.Id
                    orderby t1.CreatedOn descending
                    select new PreFiledCaseViewModel
                    {
                        Id = t1.Id,
                        RequestSubject = t1.RequestSubject,
                        UserId = t2.FirstName + " " + t2.LastName,
                        CaseTypeId = t3.DisplayName,
                        CaseNatureId = t4.DisplayName,
                        FileCaseStatusId = t5.DisplayName,
                        CreatedOn = t1.CreatedOn
                    }).ToList();
            return list;
        }

        public List<PreFiledAttachment> ReadPreFiledAttachments(string preFiledCaseId)
        {
            List<PreFiledAttachment> list = new List<PreFiledAttachment>();
            list = db.PreFiledAttachments.Where(x => x.PreFiledCaseId == preFiledCaseId).ToList();
            return list;
        }

        public PreFiledCaseViewModel GetViewModel(string Id, string type)
        {
            PreFiledCaseViewModel model = new PreFiledCaseViewModel();
            using (DefaultDBContext db = new DefaultDBContext())
            {
                PreFiledCases preFiledCase = db.PreFiledCases.Where(a => a.Id == Id).FirstOrDefault();
                model.Id = preFiledCase.Id;
                model.RequestSubject = preFiledCase.RequestSubject;
                model.UserId = preFiledCase.UserId;
                model.CaseTypeId = db.GlobalOptionSets.FirstOrDefault(x => x.Id == preFiledCase.CaseTypeId).DisplayName;
                model.CaseNatureId = db.GlobalOptionSets.FirstOrDefault(x => x.Id == preFiledCase.CaseNatureId).DisplayName;
                model.FileCaseStatusId = db.GlobalOptionSets.FirstOrDefault(x => x.Id == preFiledCase.FileCaseStatusId).DisplayName;
                model.Remarks = preFiledCase.Remarks;
                model.ApprovalRemarks = preFiledCase.ApprovalRemarks;
                model.CreatedOn = preFiledCase.CreatedOn;
                model.ModifiedOn = preFiledCase.ModifiedOn;
                if (type == "View")
                {
                    string modifiedBy = preFiledCase.ModifiedOn != null ? preFiledCase.UserId : string.Empty;
                    model.CreatedAndModified = general.GetCreatedAndModified(preFiledCase.UserId, preFiledCase.CreatedOn.ToString(), modifiedBy, preFiledCase.ModifiedOn.ToString());
                }
            }
            return model;
        }

        [CustomAuthorizeFilter(ProjectEnum.ModuleCode.PreFiledCase, "", "true", "true", "")]
        public ActionResult Edit(string Id)
        {
            PreFiledCaseViewModel model = new PreFiledCaseViewModel();
            if (Id != null)
            {
                model = GetViewModel(Id, "Edit");
            }
            model.CaseTypeSelectList = general.GetCaseTypeList(model.CaseTypeId);
            model.CaseNatureSelectList = general.GetCaseNatureList(model.CaseNatureId);
            model.FileCaseStatusSelectList = general.GetFileCaseStatusList(model.FileCaseStatusId);
            model.Attachments = ReadPreFiledAttachments(Id);
            return View(model);
        }

        [CustomAuthorizeFilter(ProjectEnum.ModuleCode.PreFiledCase, "true", "", "", "")]
        public ActionResult ViewRecord(string Id)
        {
            PreFiledCaseViewModel model = new PreFiledCaseViewModel();
            if (Id != null)
            {
                model = GetViewModel(Id, "View");
            }
            model.Attachments = ReadPreFiledAttachments(Id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(PreFiledCaseViewModel model)
        {
            ValidateModel(model);

            if (!ModelState.IsValid)
            {
                model.CaseTypeSelectList = general.GetCaseTypeList(model.CaseTypeId);
                model.CaseNatureSelectList = general.GetCaseNatureList(model.CaseNatureId);
                model.FileCaseStatusSelectList = general.GetFileCaseStatusList(model.FileCaseStatusId);
                return View(model);
            }

            SaveRecord(model);
            TempData["NotifySuccess"] = Resource.RecordSavedSuccessfully;
            return RedirectToAction("index");
        }

        public void ValidateModel(PreFiledCaseViewModel model)
        {
            if (model != null)
            {
                bool duplicated = false;
                if (model.Id != null)
                {
                    duplicated = db.PreFiledCases.Where(a => a.RequestSubject == model.RequestSubject && a.Id != model.Id).Any();
                }
                else
                {
                    duplicated = db.PreFiledCases.Where(a => a.RequestSubject == model.RequestSubject).Select(a => a.Id).Any();
                }

                if (duplicated == true)
                {
                    ModelState.AddModelError("RequestSubject", Resource.RequestSubjectAlreadyExist);
                }
            }
        }

        public void SaveRecord(PreFiledCaseViewModel model)
        {
            if (model != null)
            {
                if (model.Id != null)
                {
                    PreFiledCases prefiledCase = db.PreFiledCases.Where(a => a.Id == model.Id).FirstOrDefault();
                    prefiledCase.ApprovalRemarks = model.ApprovalRemarks;
                    prefiledCase.FileCaseStatusId = model.FileCaseStatusId;
                    db.Entry(prefiledCase).State = EntityState.Modified;
                    db.SaveChanges();
                }
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (db != null)
                {
                    db.Dispose();
                    db = null;
                }
                if (general != null)
                {
                    general.Dispose();
                    general = null;
                }
            }

            base.Dispose(disposing);
        }
    }
}

NetStarter/Views/FiledCase/Edit.cshtml
@model NetStarter.Models.PreFiledCaseViewModel
@using NetStarter.CustomHelper
@using NetStarter.Resources
@{
    if (string.IsNullOrEmpty(Model.Id))
    {
        ViewBag.Title = "File Case";
    }
    else
    {
        ViewBag.Title = "Filed Case Approval";
    }
    Layout = "~/Views/Shared/_LayoutAfterLogin.cshtml";
}

<div class="row">
    <div class="col-12">
        <div style="--bs-breadcrumb-divider: '>';">
            <ol class="breadcrumb m-0">
                <li class="breadcrumb-item fw-normal">
                    <a class="color-primarycolor opacity-50" href="@Url.Action("index")">Filed Cases</a>
                </li>
                @if (!string.IsNullOrEmpty(Model.Id))
                {
                    <li class="breadcrumb-item fw-normal"><a class="color-primarycolor opacity-50" href="@Url.Action("viewrecord", new { Id = Model.Id})">View Filed Case</a></li>
                }
                <li class="breadcrumb-item fw-normal active">@ViewBag.Title</li>
            </ol>
        </div>
        <div class="page-title-box d-sm-flex align-items-center justify-content-between pt-2">
            <h4 class="pagetitle mb-sm-0 fw600">@ViewBag.Title</h4>
        </div>
    </div>
</div>

@using (Html.BeginForm("Edit", "FiledCase", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <section class="section mt-3">
        <div class="bg-white rounded p-3 p-lg-4 p-xl-5 shadow">
            <div class="row">
                <div class="col-md-6">
                    <div class="mb-3 text-break">
                        <div class="form-group">
                            @Html.LabelFor(model => model.RequestSubject, htmlAttributes: new { @class = "form-label required fw600" })
                            @Html.EditorFor(model => model.RequestSubject, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                            @Html.ValidationMessageFor(model => model.RequestSubject, "", new { @class = "invalid-message" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    @if (Model.FileCaseStatusId == "Pending")
                    {
                        <div class="mb-3 text-break">
                            <label class="form-label required fw600" for="Case Nature">Status</label>
                            @CustomHelper.CustomDropDownList("FileCaseStatusId", Model.FileCaseStatusSelectList)
                            @Html.ValidationMessageFor(model => model.FileCaseStatusId, "", new { @class = "invalid-message" })
                        </div>
                    }
                    else
                    {
                        <div class="mb-3 text-break">
                            <div class="form-group">
                                <label class="form-label required fw600" for="Status">Status</label>
                                @Html.EditorFor(model => model.FileCaseStatusId, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                                @Html.ValidationMessageFor(model => model.FileCaseStatusId, "", new { @class = "invalid-message" })
                            </div>
                        </div>
                    }
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="mb-3 text-break">
                        <div class="form-group">
                            @Html.LabelFor(model => model.CaseTypeId, htmlAttributes: new { @class = "form-label required fw600" })
                            @Html.EditorFor(model => model.CaseTypeId, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                            @Html.ValidationMessageFor(model => model.CaseTypeId, "", new { @class = "invalid-message" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="mb-3 text-break">
                        <div class="form-group">
                            @Html.LabelFor(model => model.CaseNatureId, htmlAttributes: new { @class = "form-label required fw600" })
                            @Html.EditorFor(model => model.CaseNatureId, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                            @Html.ValidationMessageFor(model => model.CaseNatureId, "", new { @class = "invalid-message" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="row mt-2">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "form-label fw600" })
                        @Html.TextAreaFor(model => model.Remarks, htmlAttributes: new { @class = "form-control", @rows = "3", @disabled = "disabled" })
                        @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "invalid-message" })
                    </div>
                </div>
            </div>
            <hr />
            <p><strong>List of Uploaded Document(s)</strong></p>
            <div class="row">
                @if (Model.Attachments != null && Model.Attachments.Count > 0)
                {
                    <ul class="list-group">
                        @foreach (var item in Model.Attachments)
                        {
                            <li class="list-group-item">
                                @Html.DisplayFor(modelItem => item.UniqueFileName)
                                <span class="fs-19 canedit">
                                    <a href="~/Documents/@item.UniqueFileName" data-bs-placement="right" title="Download" download>
                                        <i class="fa-solid fa-download text-edit hover-color-secondarycolor" data-bs-toggle="tooltip" data-bs-placement="top" title="Download"></i>
                                    </a>
                                </span>
                            </li>
                        }
                    </ul>
                }
                else
                {
                    <i>No uploaded document yet.</i>
                }
            </div>
            <hr />
            <div class="row">
                <div class="mb-3 mt-2 text-break">
                    <div class="form-group">
                        @Html.LabelFor(model => model.ApprovalRemarks, htmlAttributes: new { @class = "form-label required fw600" })
                        @if (Model.FileCaseStatusId == "Pending")
                        {
                            @Html.EditorFor(model => model.ApprovalRemarks, new { htmlAttributes = new { @class = "form-control" } })
                        }
                        else
                        {
                            @Html.EditorFor(model => model.ApprovalRemarks, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                        }
                        @Html.ValidationMessageFor(model => model.ApprovalRemarks, "", new { @class = "invalid-message" })
                    </div>
                </div>
            </div>
            @*<hr />
        @if (Model.Attachments != null && Model.Attachments.Count > 0)
        {
            <p><strong>List of Uploaded Document(s)</strong></p>
            <ul class="list-group">
                @foreach (var item in Model.Attachments)
                {
                    <li class="list-group-item">
                        @Html.DisplayFor(modelItem => item.UniqueFileName)
                        <span class="fs-19 canedit">
                            <a href="~/Documents/@item.UniqueFileName" data-bs-placement="right" title="Download" download>
                                <i class="fa-solid fa-download text-edit hover-color-secondarycolor" data-bs-toggle="tooltip" data-bs-placement="top" title="Download"></i>
                            </a> &nbsp;
                        </span>
                        <span class="fs-19 candelete" onclick="triggerDeleteConfirmationModal('@item.UniqueFileName', '@Url.Action("deletefile", new { id= item.Id})')">
                            <i class="fa-solid fa-trash-can text-delete hover-color-secondarycolor cursor-pointer" data-bs-toggle="tooltip" data-bs-placement="top" title="Delete"></i>
                        </span>
                    </li>
                }
            </ul>
        }
        else
        {
            <i>No uploaded document yet.</i>
        }*@
        </div>
        <div class="row mt-4">
            <div class="col-12">
                <a type="button" class="btn btn-p8 bg-light hover-boxshadow me-1" href="@Url.Action("index")">@Resource.BackToList</a>
                @if (Model.SystemDefault == false && Model.FileCaseStatusId == "Pending")
                {
                    <button type="submit" class="addnewbtn btn btn-p8 hover-boxshadow hover-bg-primarycolor">@Resource.Save</button>
                }
            </div>
        </div>
    </section>
}

NetStarter/Views/FiledCase/Index.cshtml
@model NetStarter.Models.PreFiledCaseListing
@using NetStarter.Models;
@using NetStarter.Resources
@{
    ViewBag.Title = Resource.FiledCases;
    Layout = "~/Views/Shared/_LayoutAfterLogin.cshtml";
    ViewBag.TableIdPrefix = "filedcase";
    CurrentUserPermission permission = User.Identity.IsAllowed(ProjectEnum.ModuleCode.FiledCase.ToString());
}

<div class="row">
    <div class="col-12">
        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
            <h4 class="pagetitle mb-sm-0 fw600">@ViewBag.Title</h4>
        </div>
    </div>
</div>

<section class="section dashboard mt-3">
    <div class="bg-white rounded p-3 shadow">
        <div class="pb-2">
            <span id="exportToExcel" class="addnewbtn btn btn-p8 hover-boxshadow cursor-pointer hover-moveup hover-bg-primarycolor secondary-button"><i class="fa-solid fa-file-excel pe-1"></i> @Resource.ExporttoExcel</span>
            <span id="exportToPdf" class="addnewbtn btn btn-p8 hover-boxshadow cursor-pointer hover-moveup hover-bg-primarycolor secondary-button"><i class="fa-solid fa-file-pdf pe-1"></i> @Resource.ExporttoPdf</span>
        </div>
        <div class="row justify-content-between align-items-end pb-1">
            <div class="col-sm-7 col-xl-3">
                @Html.Partial("~/Views/Shared/_TableLengthDropDown.cshtml", new ViewDataDictionary { { "DropDownId", ViewBag.TableIdPrefix + "-tableDropDown" } })
            </div>
            <div class="col-xl-4"></div>
            <div class="col-xl-5 pt-2 pt-sm-0">
                <div id="searchinput" class="input-group flex-nowrap">
                    @Html.TextBox("search", "", htmlAttributes: new { type = "text", @class = "form-control", @placeholder = Resource.SearchDot })
                    <button type="button" class="input-group-text bg-transparent hover-bg-primarycolor hover-color-white" id="searchbtn"><i class="fa-solid fa-magnifying-glass pe-1"></i> @Resource.Search</button>
                    <button type="button" class="input-group-text bg-transparent hover-bg-primarycolor hover-color-white" id="resetbtn"><i class="fa-solid fa-rotate-left pe-1"></i> @Resource.Reset</button>
                </div>
            </div>
        </div>
        <div id="@ViewBag.TableIdPrefix-table-wrapper">
            <div class="table-responsive">
                <table id="@ViewBag.TableIdPrefix-table" class="table table-hover align-middle mb-0">
                    <thead class="table-light">
                        <tr>
                            <th class="thead"></th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                <div class="spinner d-flex justify-content-center align-items-center text-center color-primarycolor py-5">
                    <div class="spinner-border ml-auto" role="status" aria-hidden="true"></div><strong> &nbsp; @Resource.Loading </strong>
                </div>
            </div>
            <div class="dummyfooter row justify-content-between">
                <div class="col-md-6">@Resource.Showing0Entries</div>
                <div class="col-md-6 text-end">@Resource.Page0OfPage0</div>
            </div>
        </div>
    </div>
</section>

@section scripts{
    <script>
        var tableIdPrefix = "@ViewBag.TableIdPrefix";
        var canView = "@permission.ViewRight";
        var canAdd = "@permission.AddRight";
        var canEdit = "@permission.EditRight";
        var canDelete = "@permission.DeleteRight";

        $(document).ready(function(){
            var url = "@(Html.Raw(Url.Action("GetPartialViewFiledCases", "FiledCase")))";
            $("#" + tableIdPrefix +"-table").load(url, function(responseTxt, statusTxt, xhr){
                if (statusTxt == "success") {
                    hideDummySpinnerHeaderFooter(tableIdPrefix+"-table-wrapper");
                }
                if (statusTxt == "error") {
                    //no record in database
                    if (xhr.status == 500) {
                        hideDummySpinnerHeaderFooter(tableIdPrefix+"-table-wrapper");
                        var table = $("#" + tableIdPrefix +"-table").DataTable({ dom: 'rtip', "pageLength": 10 });
                    }
                }
              });
        });
    </script>
}

NetStarter/Views/FiledCase/ViewRecord.cshtml
@model NetStarter.Models.PreFiledCaseViewModel
@using NetStarter.CustomHelper
@using NetStarter.Models
@using NetStarter.Resources
@{
    ViewBag.Title = "View Filed Case";
    ViewBag.Module = "Filed Case";
    Layout = "~/Views/Shared/_LayoutAfterLogin.cshtml";
    CurrentUserPermission permission = User.Identity.IsAllowed(ProjectEnum.ModuleCode.FiledCase.ToString());
}

<div class="row">
    <div class="col-12">
        <div style="--bs-breadcrumb-divider: '>';">
            <ol class="breadcrumb m-0">
                <li class="breadcrumb-item fw-normal"><a class="color-primarycolor opacity-50" href="@Url.Action("index")">Filed Cases</a></li>
                <li class="breadcrumb-item fw-normal active">@ViewBag.Title</li>
            </ol>
        </div>
        <div class="page-title-box d-sm-flex align-items-center justify-content-between pt-2">
            <h4 class="pagetitle mb-sm-0 fw600">@ViewBag.Title</h4>
            <div class="d-flex">
                @if (permission.EditRight && Model.SystemDefault == false)
                {
                    <span class="fs-19">
                    <a href="@Url.Action("edit", new { Id = Model.Id })">
                        <i class="fa-solid fa-edit text-edit hover-color-secondarycolor" data-bs-toggle="tooltip" data-bs-placement="top" title="@Resource.Edit"></i></a>
                    </span>
                }
                @if (permission.DeleteRight && Model.SystemDefault == false)
                {
                    <span class="fs-19">&nbsp; <i onclick="triggerDeleteConfirmationModal('@Model.RequestSubject', '@Url.Action("delete", new { id=Model.Id})')" class="fa-solid fa-trash-can text-delete cursor-pointer hover-color-secondarycolor" data-bs-toggle="tooltip" data-bs-placement="top" title="@Resource.Delete"></i></span>
                }
            </div>
        </div>
    </div>
</div>

<section class="section mt-3">
    <div class="bg-white rounded p-3 p-lg-4 p-xl-5 shadow">
        <h2 class="fs-20 fw600 mb-4">@ViewBag.Module @Resource.Information</h2>
        <div class="row">
            <div class="col-md-6">
                <div class="mb-3 text-break">
                    <div>@Html.LabelFor(model => model.RequestSubject, htmlAttributes: new { @class = "fw600" })</div>
                    <div>@Html.DisplayFor(model => model.RequestSubject, new { htmlAttributes = new { @class = "form-control d-block" } })</div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="mb-3 text-break">
                    <div>@Html.LabelFor(model => model.FileCaseStatusId, htmlAttributes: new { @class = "fw600" })</div>
                    <div>@Html.DisplayFor(model => model.FileCaseStatusId, new { htmlAttributes = new { @class = "form-control" } })</div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="mb-3 text-break">
                    <div>@Html.LabelFor(model => model.CaseTypeId, htmlAttributes: new { @class = "fw600" })</div>
                    <div>@Html.DisplayFor(model => model.CaseTypeId, new { htmlAttributes = new { @class = "form-control" } })</div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="mb-3 text-break">
                    <div>@Html.LabelFor(model => model.CaseNatureId, htmlAttributes: new { @class = "fw600" })</div>
                    <div>@Html.DisplayFor(model => model.CaseNatureId, new { htmlAttributes = new { @class = "form-control d-block" } })</div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="mb-3 text-break">
                    <div>@Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "fw600" })</div>
                    <div>@Html.DisplayFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control" } })</div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="mb-3 text-break">
                    <div>@Html.LabelFor(model => model.ApprovalRemarks, htmlAttributes: new { @class = "fw600" })</div>
                    <div>@Html.DisplayFor(model => model.ApprovalRemarks, new { htmlAttributes = new { @class = "form-control d-block" } })</div>
                </div>
            </div>
        </div>
        <p><strong>List of Uploaded Document(s)</strong></p>
        <div class="row">
            @if (Model.Attachments.Count > 0)
            {

                <ul class="list-group">
                    @foreach (var item in Model.Attachments)
                    {
                        <li class="list-group-item">
                            @Html.DisplayFor(modelItem => item.UniqueFileName)
                        </li>
                    }
                </ul>
            }
            else
            {
                <i>No uploaded document yet.</i>
            }
        </div>
    </div>
    <div class="bg-white rounded p-3 p-lg-4 p-xl-5 shadow mt-4">
        <h2 class="fs-20 fw600 mb-4">@Resource.OtherInformation</h2>
        <div class="row">
            <div class="col-md-6">
                <div class="mb-3 text-break">
                    <div>@Html.LabelFor(model => model.CreatedAndModified.CreatedByName, htmlAttributes: new { @class = "fw600" })</div>
                    <div>@Html.DisplayFor(model => model.CreatedAndModified.CreatedByName, new { htmlAttributes = new { @class = "form-control" } })</div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="mb-3 text-break">
                    <div>@Html.LabelFor(model => model.CreatedAndModified.FormattedCreatedOn, htmlAttributes: new { @class = "fw600" })</div>
                    <div>@Html.DisplayFor(model => model.CreatedAndModified.FormattedCreatedOn, new { htmlAttributes = new { @class = "form-control" } })</div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="mb-3 text-break">
                    <div>@Html.LabelFor(model => model.CreatedAndModified.ModifiedByName, htmlAttributes: new { @class = "fw600" })</div>
                    <div>@Html.DisplayFor(model => model.CreatedAndModified.ModifiedByName, new { htmlAttributes = new { @class = "form-control" } })</div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="mb-3 text-break">
                    <div>@Html.LabelFor(model => model.CreatedAndModified.FormattedModifiedOn, htmlAttributes: new { @class = "fw600" })</div>
                    <div>@Html.DisplayFor(model => model.CreatedAndModified.FormattedModifiedOn, new { htmlAttributes = new { @class = "form-control" } })</div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-12">
            <a class="btn btn-p8 bg-light hover-boxshadow me-1" href="@Url.Action("index")">@Resource.BackToList</a>
            @if (permission.EditRight && Model.SystemDefault == false)
            {
                <a class="btn btn-p8 hover-boxshadow me-1 addnewbtn hover-bg-primarycolor" href="@Url.Action("edit", new { Id = Model.Id})">@Resource.Edit @ViewBag.Module</a>
            }
        </div>
    </div>
</section>